name: Go
on:
  push:
    branches: [ main ]
    paths: '**.go'
  pull_request:
    branches: [ main ]
    paths: '**.go'
jobs:
  Go:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          workdir: algorithms/Go
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
