name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check . || true
      - run: codespell --ignore-words-list="ans,nnumber,nin" --quiet-level=2  # --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --check-only --profile black .
      - run: pip install -r requirements.txt || true
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
