name: Python
on:
  push:
    branches: [ main ]
    paths: '**.py'
  pull_request:
    branches: [ main ]
    paths: '**.py'
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check . || true
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --check-only --profile black .
      - run: pip install -r requirements.txt || true
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
